import Footer from "@/components/footer/Footer";
import Header from "@/components/header";
// import { Inter } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Foreware Technology",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="body" >
        <div className="header"><Header /></div>
        {children}
        <div className="footer"><Footer /></div>
      </body>
    </html>
  );
}
